# Generated by Django 2.2.16 on 2020-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200910_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='products.Category', verbose_name='Дочерняя категория'),
        ),
    ]
